

analyze_financial_statements_task:
  description: >
    Analyze the financial statements of {company_name} for the past {time_period} years.
    Focus on:
    1. Balance sheet health and trends
    2. Income statement performance and quality of earnings
    3. Cash flow analysis and conversion rates
    4. Key financial ratios (liquidity, solvency, profitability)
    5. Year-over-year and quarter-over-quarter changes
    6. Red flags or accounting concerns
    
    Relevant financial data:
    {collected_financial_data}
  expected_output: >
    A comprehensive analysis of the company's financial statements with key metrics, trends,
    strengths, weaknesses, and potential red flags clearly identified. Include specific data
    points to support your conclusions.
  agent: financial_statement_analyst
  context:
    - collect_financial_data_task

calculate_valuation_metrics_task:
  description: >
    Calculate and analyze valuation metrics for {ticker} ({company_name}).
    
    Current stock price: ${current_price}
    Industry: {industry}
    
    Your analysis should include:
    1. Price-based multiples (P/E, P/S, P/B, P/FCF)
    2. Enterprise value multiples (EV/EBITDA, EV/Sales, EV/FCF)
    3. Comparison to historical averages (5-year and 10-year)
    4. Comparison to industry peers and sector averages
    5. Dividend yield and payout ratio assessment (if applicable)
    6. Interpretation of current valuation relative to growth and quality
    
    Financial data:
    {collected_financial_data}
    
    Industry comparison data:
    {industry_data}
  expected_output: >
    A detailed valuation analysis with calculated metrics, historical and peer comparisons,
    and an assessment of whether the current stock price represents fair value, overvaluation,
    or undervaluation. Include specific numerical support for your conclusions.
  agent: valuation_expert
  context:
    - collect_financial_data_task
    - analyze_financial_statements_task

assess_growth_potential_task:
  description: >
    Evaluate the historical growth and future growth potential of {ticker} ({company_name}).
    
    Your analysis should include:
    1. Historical growth rates (revenue, earnings, cash flow, EBITDA)
    2. Quality and consistency of past growth
    3. Total addressable market (TAM) and current market share
    4. Growth drivers and catalysts
    5. Challenges or headwinds to future growth
    6. Realistic growth projections for the next 3-5 years
    
    Company information:
    {company_info}
    
    Financial data:
    {collected_financial_data}
    
    Industry trends:
    {industry_trends}
  expected_output: >
    A thorough assessment of the company's growth trajectory with quantified historical
    growth rates, detailed analysis of growth quality, and well-supported projections
    for future growth potential.
  agent: growth_analyst
  context:
    - collect_financial_data_task
    - analyze_financial_statements_task

evaluate_competitive_position_task:
  description: >
    Analyze the competitive position and advantages of {ticker} ({company_name}) within its industry.
    
    Your analysis should include:
    1. Identification of key competitors
    2. Market share analysis and trends
    3. Sources of competitive advantage (if any)
    4. Application of Porter's Five Forces framework
    5. Assessment of pricing power and margin sustainability
    6. Barriers to entry protecting the business
    7. Vulnerability to disruption or technological change
    
    Company information:
    {company_info}
    
    Financial data:
    {collected_financial_data}
    
    Industry analysis:
    {industry_analysis}
    
    Competitor data:
    {competitor_data}
  expected_output: >
    A comprehensive evaluation of the company's competitive positioning with
    specific evidence of any sustainable advantages, vulnerabilities, and how
    these factors impact long-term business value.
  agent: competitive_advantage_assessor
  context:
    - collect_financial_data_task
    - analyze_financial_statements_task
    - assess_growth_potential_task

review_capital_allocation_task:
  description: >
    Evaluate the capital allocation decisions and effectiveness of {ticker} ({company_name}) management.
    
    Your analysis should include:
    1. Return on invested capital (ROIC) trends
    2. Capital expenditure patterns and efficiency
    3. Dividend policy and history (if applicable)
    4. Share repurchase programs and timing effectiveness
    5. M&A history and value creation/destruction
    6. Debt management and capital structure decisions
    7. Overall assessment of management's capital allocation skill
    
    Financial data:
    {collected_financial_data}
    
    Management history:
    {management_history}
    
    Capital allocation actions:
    {capital_allocation_data}
  expected_output: >
    A detailed analysis of management's capital allocation decisions with quantitative
    assessment of returns generated, effectiveness of various capital deployment strategies,
    and an overall rating of management's capital allocation capabilities.
  agent: capital_allocation_analyst
  context:
    - collect_financial_data_task
    - analyze_financial_statements_task
    - assess_growth_potential_task

synthesize_fundamental_analysis_task:
  description: >
    Synthesize all fundamental analysis findings for {ticker} ({company_name}) into a comprehensive investment assessment.
    
    Your synthesis should:
    1. Integrate key findings from all previous analyses
    2. Identify the most critical factors affecting investment potential
    3. Highlight primary strengths and weaknesses
    4. Assess overall fundamental quality on a 1-10 scale
    5. Provide a balanced view of risks and opportunities
    6. Formulate actionable conclusions for investment decision-making
    
    Previous analyses:
    - Financial Statement Analysis: {financial_statement_analysis}
    - Valuation Assessment: {valuation_assessment}
    - Growth Potential: {growth_potential_analysis}
    - Competitive Position: {competitive_position_analysis}
    - Capital Allocation Review: {capital_allocation_review}
  expected_output: >
    A comprehensive synthesis of all fundamental analyses with clear priorities
    assigned to different factors, an overall fundamental quality rating,
    and specific actionable conclusions about the investment merits of the company.
  agent: fundamental_synthesis_agent
  context:
    - collect_financial_data_task
    - analyze_financial_statements_task
    - calculate_valuation_metrics_task
    - assess_growth_potential_task
    - evaluate_competitive_position_task
    - review_capital_allocation_task